name: Generate Doxygen Documentation and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for gh-pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----- INSTALLATION -----
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Install Graphviz (Dot)
        run: sudo apt-get install graphviz -y

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      # ----- TESTS UNITAIRES -----
      - name: Run unit tests and generate HTML report
        run: |
          pytest tests/test_app.py --html=report.html
        env:
          CI: true

      # ----- DOXYGEN -----
      - name: Generate Doxygen documentation
        run: doxygen config/Doxyfile

      # ----- DEPLOIEMENT -----
      - name: Deploy Doxygen documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
